-- ----------------------------------------------------------------------------
-- Base LIBRAIRIE : une chaîne de librairies imaginaire (données fictives)
-- ----------------------------------------------------------------------------

DROP TABLE LIB_LIGNE_LIV CASCADE CONSTRAINTS;
DROP TABLE LIB_LIVRAISON CASCADE CONSTRAINTS;
DROP TABLE LIB_LIGNE_CDE CASCADE CONSTRAINTS;
DROP TABLE LIB_COMMANDE CASCADE CONSTRAINTS;
DROP TABLE LIB_LIVRE CASCADE CONSTRAINTS;
DROP TABLE LIB_EDITEUR CASCADE CONSTRAINTS;
DROP TABLE LIB_BOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE LIB_CLIENT CASCADE CONSTRAINTS;

CREATE TABLE LIB_CLIENT
(
    CL_NUMERO            VARCHAR2(4),
    CL_NOM               VARCHAR2(30),
    CL_PRENOM            VARCHAR2(30),
    CL_VILLE             VARCHAR2(30),
    CL_PAYS              VARCHAR2(20),
    CL_CA                NUMBER(9,2),
    CL_TYPE              CHAR(1),
    CONSTRAINT PK_LIB_CLIENT PRIMARY KEY (CL_NUMERO)
);

CREATE TABLE LIB_BOUTIQUE
(
    BO_NUMERO            VARCHAR2(4),
    BO_VILLE             VARCHAR2(30),
    BO_NOM_GERANT        VARCHAR2(30),
    BO_PRENOM_GERANT     VARCHAR2(30),
    CONSTRAINT PK_LIB_BOUTIQUE PRIMARY KEY (BO_NUMERO)
);

CREATE TABLE LIB_EDITEUR
(
    ED_NUMERO            VARCHAR2(4),
    ED_NOM               VARCHAR2(30),
    CONSTRAINT PK_LIB_EDITEUR PRIMARY KEY (ED_NUMERO)
);

CREATE TABLE LIB_LIVRE
(
    LI_NUMERO            VARCHAR2(4),
    ED_NUMERO            VARCHAR2(4),
    LI_TITRE             VARCHAR2(40),
    LI_PAGES             NUMBER(5),
    LI_GENRE             VARCHAR2(15),
    LI_STOCK             NUMBER(5),
    LI_PRIX_ACHAT        NUMBER(7,2),
    LI_PRIX_VENTE        NUMBER(7,2),
    CONSTRAINT PK_LIB_LIVRE PRIMARY KEY (LI_NUMERO)
);

CREATE TABLE LIB_COMMANDE
(
    CO_NUMERO            VARCHAR2(4),
    CO_DATE              DATE,
    BO_NUMERO            VARCHAR2(4),
    CL_NUMERO            VARCHAR2(4),
    CONSTRAINT PK_LIB_COMMANDE PRIMARY KEY (CO_NUMERO)
);

CREATE TABLE LIB_LIGNE_CDE
(
    CO_NUMERO            VARCHAR2(4),
    LI_NUMERO            VARCHAR2(4),
    QTE_CMDEE            NUMBER(5),
    QTE_LIVREE           NUMBER(5),
    PRIX_UNITAIRE        NUMBER(7,2),
    DATE_LIV             DATE,
    CONSTRAINT PK_LIB_LIGNE_CDE PRIMARY KEY (CO_NUMERO, LI_NUMERO)
);

CREATE TABLE LIB_LIVRAISON
(
    LV_NUMERO            VARCHAR2(4),
    BO_NUMERO            VARCHAR2(4),
    CO_NUMERO            VARCHAR2(4),
    CL_NUMERO            VARCHAR2(4),
    DATE_LIV             DATE,
    CONSTRAINT PK_LIB_LIVRAISON PRIMARY KEY (LV_NUMERO)
);

CREATE TABLE LIB_LIGNE_LIV
(
    LV_NUMERO            VARCHAR2(4),
    LI_NUMERO            VARCHAR2(4),
    QTE_LIVREE           NUMBER(5),
    CONSTRAINT PK_LIB_LIGNE_LIV PRIMARY KEY (LV_NUMERO, LI_NUMERO)
);

ALTER TABLE LIB_LIVRE ADD CONSTRAINT FK_LIB_LIVRE_1 FOREIGN KEY (ED_NUMERO) REFERENCES LIB_EDITEUR (ED_NUMERO);
ALTER TABLE LIB_COMMANDE ADD CONSTRAINT FK_LIB_COMMANDE_1 FOREIGN KEY (BO_NUMERO) REFERENCES LIB_BOUTIQUE (BO_NUMERO);
ALTER TABLE LIB_COMMANDE ADD CONSTRAINT FK_LIB_COMMANDE_2 FOREIGN KEY (CL_NUMERO) REFERENCES LIB_CLIENT (CL_NUMERO);
ALTER TABLE LIB_LIGNE_CDE ADD CONSTRAINT FK_LIB_LIGNE_CDE_1 FOREIGN KEY (CO_NUMERO) REFERENCES LIB_COMMANDE (CO_NUMERO);
ALTER TABLE LIB_LIGNE_CDE ADD CONSTRAINT FK_LIB_LIGNE_CDE_2 FOREIGN KEY (LI_NUMERO) REFERENCES LIB_LIVRE (LI_NUMERO);
ALTER TABLE LIB_LIVRAISON ADD CONSTRAINT FK_LIB_LIVRAISON_1 FOREIGN KEY (BO_NUMERO) REFERENCES LIB_BOUTIQUE (BO_NUMERO);
ALTER TABLE LIB_LIVRAISON ADD CONSTRAINT FK_LIB_LIVRAISON_2 FOREIGN KEY (CO_NUMERO) REFERENCES LIB_COMMANDE (CO_NUMERO);
ALTER TABLE LIB_LIVRAISON ADD CONSTRAINT FK_LIB_LIVRAISON_3 FOREIGN KEY (CL_NUMERO) REFERENCES LIB_CLIENT (CL_NUMERO);
ALTER TABLE LIB_LIGNE_LIV ADD CONSTRAINT FK_LIB_LIGNE_LIV_1 FOREIGN KEY (LV_NUMERO) REFERENCES LIB_LIVRAISON (LV_NUMERO);
ALTER TABLE LIB_LIGNE_LIV ADD CONSTRAINT FK_LIB_LIGNE_LIV_2 FOREIGN KEY (LI_NUMERO) REFERENCES LIB_LIVRE (LI_NUMERO);

-- LIB_CLIENT (10 lignes)
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C01','LEBRUN','Alice','CAEN','FRANCE',2500.0,'P');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C02','HAMON','Yann','CHERBOURG','FRANCE',830.5,'P');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C03','LYCEE MALHERBE','Service achats','CAEN','FRANCE',4300.0,'E');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C04','PEETERS','Lars','BRUXELLES','BELGIQUE',1580.0,'P');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C05','MOREL','Julien','ROUEN','FRANCE',0,'P');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C06','SANTOS','Ana','LISBONNE','PORTUGAL',210.0,'P');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C07','MEDIATHEQUE DU PORT','Accueil','CAEN','FRANCE',6400.0,'E');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C08','BERNARD','Inès','SAINT-LO','FRANCE',null,'P');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C09','COLLEGE DES ALPES','Intendance','GENEVE','SUISSE',9900.0,'E');
insert into LIB_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_VILLE,CL_PAYS,CL_CA,CL_TYPE) values ('C10','LEBRUN','Marc','CHERBOURG','FRANCE',300.0,'P');

-- LIB_BOUTIQUE (4 lignes)
insert into LIB_BOUTIQUE (BO_NUMERO,BO_VILLE,BO_NOM_GERANT,BO_PRENOM_GERANT) values ('B01','CAEN','GOSSELIN','Pierre');
insert into LIB_BOUTIQUE (BO_NUMERO,BO_VILLE,BO_NOM_GERANT,BO_PRENOM_GERANT) values ('B02','CHERBOURG','LEMOINE','Sophie');
insert into LIB_BOUTIQUE (BO_NUMERO,BO_VILLE,BO_NOM_GERANT,BO_PRENOM_GERANT) values ('B03','ROUEN','FONTAINE','Karim');
insert into LIB_BOUTIQUE (BO_NUMERO,BO_VILLE,BO_NOM_GERANT,BO_PRENOM_GERANT) values ('B04','BAYEUX','GOSSELIN','Marie');

-- LIB_EDITEUR (7 lignes)
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E01','EDITIONS DU COTENTIN');
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E02','PLUME ET ENCRE');
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E03','LIVRES DE POCHE NORMANDS');
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E04','SCIENCES POUR TOUS');
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E05','BULLES ET CASES');
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E06','ATLAS VOYAGES');
insert into LIB_EDITEUR (ED_NUMERO,ED_NOM) values ('E07','PRESSES DU BOCAGE');

-- LIB_LIVRE (20 lignes)
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L01','E02','LE PHARE DES BRUMES',320,'ROMAN',40,9.5,19.9);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L02','E03','LE PHARE DES BRUMES',320,'ROMAN',120,3.2,7.9);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L03','E02','LA MAISON DU GUETTEUR',410,'ROMAN',15,11.0,22.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L04','E04','LES BASES DE DONNEES',280,'SCIENCES',25,14.0,29.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L05','E04','ALGORITHMIQUE FACILE',350,'SCIENCES',30,15.5,32.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L06','E04','LE CIEL A L''OEIL NU',190,'SCIENCES',12,8.0,18.5);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L07','E05','CAPITAINE GALET',48,'BD',60,6.0,12.9);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L08','E05','LES ROBOTS DE MINUIT',56,'BD',45,6.5,13.9);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L09','E05','CAPITAINE GALET 2',48,'BD',35,6.0,12.9);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L10','E01','CHEMINS DU COTENTIN',220,'GUIDE',50,7.5,16.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L11','E06','CHEMINS DU COTENTIN',240,'GUIDE',20,8.0,17.5);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L12','E01','CUISINE DE LA MANCHE',160,'CUISINE',18,9.0,21.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L13','E01','CARNET DE MAREES',96,null,70,2.5,6.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L14','E06','MAROC EN 4X4',300,'GUIDE',10,12.0,26.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L15','E06','ISLANDE A PIED',280,'GUIDE',8,12.0,26.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L16','E03','POEMES DE LA COTE',120,'POESIE',25,2.0,5.5);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L17','E02','ATLAS DES PHARES',520,'BEAU LIVRE',5,22.0,45.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L18','E02','ENCYCLOPEDIE DE LA MER',1200,'BEAU LIVRE',3,45.0,89.0);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L19','E03','MARQUE-PAGES ILLUSTRES',2,'PAPETERIE',300,null,1.5);
insert into LIB_LIVRE (LI_NUMERO,ED_NUMERO,LI_TITRE,LI_PAGES,LI_GENRE,LI_STOCK,LI_PRIX_ACHAT,LI_PRIX_VENTE) values ('L20','E03','LE PETIT LEXIQUE',64,null,150,null,3.0);

-- LIB_COMMANDE (12 lignes)
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K01',to_date('08/01/2025','DD/MM/YYYY'),'B01','C01');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K02',to_date('15/01/2025','DD/MM/YYYY'),'B01','C03');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K03',to_date('03/02/2025','DD/MM/YYYY'),'B02','C02');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K04',to_date('20/02/2025','DD/MM/YYYY'),'B01','C01');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K05',to_date('11/03/2025','DD/MM/YYYY'),'B03','C04');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K06',to_date('28/03/2025','DD/MM/YYYY'),'B02','C10');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K07',to_date('02/04/2025','DD/MM/YYYY'),'B01','C07');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K08',to_date('14/05/2025','DD/MM/YYYY'),'B03','C09');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K09',to_date('05/06/2025','DD/MM/YYYY'),'B04','C06');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K10',to_date('30/06/2025','DD/MM/YYYY'),'B01','C03');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K11',to_date('09/09/2025','DD/MM/YYYY'),'B02','C02');
insert into LIB_COMMANDE (CO_NUMERO,CO_DATE,BO_NUMERO,CL_NUMERO) values ('K12',to_date('01/10/2025','DD/MM/YYYY'),'B01','C01');

-- LIB_LIGNE_CDE (25 lignes)
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K01','L04',2,2,29.0,to_date('10/01/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K01','L01',1,1,19.9,to_date('10/01/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K01','L07',2,2,12.9,to_date('10/01/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K02','L10',30,30,16.0,to_date('20/01/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K02','L12',5,5,21.0,to_date('20/01/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K03','L03',1,1,22.0,to_date('06/02/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K03','L06',1,1,18.5,to_date('06/02/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K04','L14',1,1,26.0,to_date('25/02/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K04','L04',4,3,29.0,to_date('25/02/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K05','L18',1,1,89.0,to_date('18/03/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K05','L17',1,1,45.0,to_date('18/03/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K05','L05',2,2,32.0,to_date('18/03/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K06','L02',3,3,7.9,to_date('01/04/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K07','L09',10,10,12.9,to_date('03/04/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K07','L16',4,4,5.5,to_date('03/04/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K07','L11',3,3,17.5,to_date('03/04/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K08','L15',12,12,26.0,to_date('20/05/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K08','L08',30,30,13.9,to_date('20/05/2025','DD/MM/YYYY'));
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K09','L01',2,0,19.9,null);
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K09','L06',1,0,18.5,null);
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K10','L04',25,0,29.0,null);
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K10','L13',40,0,6.0,null);
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K11','L07',1,0,12.9,null);
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K12','L18',1,0,89.0,null);
insert into LIB_LIGNE_CDE (CO_NUMERO,LI_NUMERO,QTE_CMDEE,QTE_LIVREE,PRIX_UNITAIRE,DATE_LIV) values ('K12','L14',2,0,26.0,null);

-- LIB_LIVRAISON (8 lignes)
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V01','B01','K01','C01',to_date('10/01/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V02','B01','K02','C03',to_date('20/01/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V03','B02','K03','C02',to_date('06/02/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V04','B01','K04','C01',to_date('25/02/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V05','B03','K05','C04',to_date('18/03/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V06','B02','K06','C10',to_date('01/04/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V07','B01','K07','C07',to_date('03/04/2025','DD/MM/YYYY'));
insert into LIB_LIVRAISON (LV_NUMERO,BO_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('V08','B03','K08','C09',to_date('20/05/2025','DD/MM/YYYY'));

-- LIB_LIGNE_LIV (18 lignes)
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V01','L04',2);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V01','L01',1);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V01','L07',2);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V02','L10',30);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V02','L12',5);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V03','L03',1);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V03','L06',1);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V04','L14',1);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V04','L04',3);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V05','L18',1);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V05','L17',1);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V05','L05',2);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V06','L02',3);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V07','L09',10);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V07','L16',4);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V07','L11',3);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V08','L15',12);
insert into LIB_LIGNE_LIV (LV_NUMERO,LI_NUMERO,QTE_LIVREE) values ('V08','L08',30);

commit;
