-- ----------------------------------------------------------------------------
-- Base BUR : magasin de fournitures de bureau fictif (même structure que la base CDI du cours)
-- ----------------------------------------------------------------------------

DROP TABLE BUR_LIGLIV CASCADE CONSTRAINTS;
DROP TABLE BUR_LIVRAISON CASCADE CONSTRAINTS;
DROP TABLE BUR_LIGCDE CASCADE CONSTRAINTS;
DROP TABLE BUR_COMMANDE CASCADE CONSTRAINTS;
DROP TABLE BUR_ARTICLE CASCADE CONSTRAINTS;
DROP TABLE BUR_FOURNISSEUR CASCADE CONSTRAINTS;
DROP TABLE BUR_MAGASIN CASCADE CONSTRAINTS;
DROP TABLE BUR_CLIENT CASCADE CONSTRAINTS;

CREATE TABLE BUR_CLIENT
(
    CL_NUMERO            VARCHAR2(4),
    CL_NOM               VARCHAR2(30),
    CL_PRENOM            VARCHAR2(30),
    CL_LOCALITE          VARCHAR2(30),
    CL_PAYS              VARCHAR2(20),
    CL_CA                NUMBER(9,2),
    CL_TYPE              CHAR(1),
    CONSTRAINT PK_BUR_CLIENT PRIMARY KEY (CL_NUMERO)
);

CREATE TABLE BUR_MAGASIN
(
    MA_NUMERO            VARCHAR2(4),
    MA_LOCALITE          VARCHAR2(30),
    MA_NOM_GERANT        VARCHAR2(30),
    MA_PRENOM_GERANT     VARCHAR2(30),
    CONSTRAINT PK_BUR_MAGASIN PRIMARY KEY (MA_NUMERO)
);

CREATE TABLE BUR_FOURNISSEUR
(
    FO_NUMERO            VARCHAR2(4),
    FO_NOM               VARCHAR2(30),
    CONSTRAINT PK_BUR_FOURNISSEUR PRIMARY KEY (FO_NUMERO)
);

CREATE TABLE BUR_ARTICLE
(
    AR_NUMERO            VARCHAR2(4),
    FO_NUMERO            VARCHAR2(4),
    AR_NOM               VARCHAR2(30),
    AR_POIDS             NUMBER(6),
    AR_COULEUR           VARCHAR2(10),
    AR_STOCK             NUMBER(5),
    AR_PA                NUMBER(7,2),
    AR_PV                NUMBER(7,2),
    CONSTRAINT PK_BUR_ARTICLE PRIMARY KEY (AR_NUMERO)
);

CREATE TABLE BUR_COMMANDE
(
    CO_NUMERO            VARCHAR2(4),
    CO_DATE              DATE,
    MA_NUMERO            VARCHAR2(4),
    CL_NUMERO            VARCHAR2(4),
    CONSTRAINT PK_BUR_COMMANDE PRIMARY KEY (CO_NUMERO)
);

CREATE TABLE BUR_LIGCDE
(
    CO_NUMERO            VARCHAR2(4),
    AR_NUMERO            VARCHAR2(4),
    LIC_QTCMDEE          NUMBER(5),
    LIC_QTLIVREE         NUMBER(5),
    LIC_PU               NUMBER(7,2),
    DATE_LIV             DATE,
    CONSTRAINT PK_BUR_LIGCDE PRIMARY KEY (CO_NUMERO, AR_NUMERO)
);

CREATE TABLE BUR_LIVRAISON
(
    LI_NUMERO            VARCHAR2(4),
    MA_NUMERO            VARCHAR2(4),
    CO_NUMERO            VARCHAR2(4),
    CL_NUMERO            VARCHAR2(4),
    DATE_LIV             DATE,
    CONSTRAINT PK_BUR_LIVRAISON PRIMARY KEY (LI_NUMERO)
);

CREATE TABLE BUR_LIGLIV
(
    LI_NUMERO            VARCHAR2(4),
    AR_NUMERO            VARCHAR2(4),
    LIL_QTLIVREE         NUMBER(5),
    CONSTRAINT PK_BUR_LIGLIV PRIMARY KEY (LI_NUMERO, AR_NUMERO)
);

ALTER TABLE BUR_ARTICLE ADD CONSTRAINT FK_BUR_ARTICLE_1 FOREIGN KEY (FO_NUMERO) REFERENCES BUR_FOURNISSEUR (FO_NUMERO);
ALTER TABLE BUR_COMMANDE ADD CONSTRAINT FK_BUR_COMMANDE_1 FOREIGN KEY (MA_NUMERO) REFERENCES BUR_MAGASIN (MA_NUMERO);
ALTER TABLE BUR_COMMANDE ADD CONSTRAINT FK_BUR_COMMANDE_2 FOREIGN KEY (CL_NUMERO) REFERENCES BUR_CLIENT (CL_NUMERO);
ALTER TABLE BUR_LIGCDE ADD CONSTRAINT FK_BUR_LIGCDE_1 FOREIGN KEY (CO_NUMERO) REFERENCES BUR_COMMANDE (CO_NUMERO);
ALTER TABLE BUR_LIGCDE ADD CONSTRAINT FK_BUR_LIGCDE_2 FOREIGN KEY (AR_NUMERO) REFERENCES BUR_ARTICLE (AR_NUMERO);
ALTER TABLE BUR_LIVRAISON ADD CONSTRAINT FK_BUR_LIVRAISON_1 FOREIGN KEY (MA_NUMERO) REFERENCES BUR_MAGASIN (MA_NUMERO);
ALTER TABLE BUR_LIVRAISON ADD CONSTRAINT FK_BUR_LIVRAISON_2 FOREIGN KEY (CO_NUMERO) REFERENCES BUR_COMMANDE (CO_NUMERO);
ALTER TABLE BUR_LIVRAISON ADD CONSTRAINT FK_BUR_LIVRAISON_3 FOREIGN KEY (CL_NUMERO) REFERENCES BUR_CLIENT (CL_NUMERO);
ALTER TABLE BUR_LIGLIV ADD CONSTRAINT FK_BUR_LIGLIV_1 FOREIGN KEY (LI_NUMERO) REFERENCES BUR_LIVRAISON (LI_NUMERO);
ALTER TABLE BUR_LIGLIV ADD CONSTRAINT FK_BUR_LIGLIV_2 FOREIGN KEY (AR_NUMERO) REFERENCES BUR_ARTICLE (AR_NUMERO);

-- BUR_CLIENT (10 lignes)
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C01','LEBRUN','Alice','CAEN','FRANCE',12500.0,'E');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C02','HAMON','Yann','CHERBOURG','FRANCE',830.5,'P');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C03','DUBOIS','Claire','CAEN','FRANCE',4300.0,'E');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C04','PEETERS','Lars','BRUXELLES','BELGIQUE',15800.0,'E');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C05','MOREL','Julien','ROUEN','FRANCE',0,'P');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C06','SANTOS','Ana','LISBONNE','PORTUGAL',2100.0,'P');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C07','LECLERC','Hugo','CAEN','FRANCE',640.0,'P');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C08','BERNARD','Inès','SAINT-LO','FRANCE',null,'P');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C09','MULLER','Jonas','GENEVE','SUISSE',9900.0,'E');
insert into BUR_CLIENT (CL_NUMERO,CL_NOM,CL_PRENOM,CL_LOCALITE,CL_PAYS,CL_CA,CL_TYPE) values ('C10','LEBRUN','Marc','CHERBOURG','FRANCE',300.0,'P');

-- BUR_MAGASIN (4 lignes)
insert into BUR_MAGASIN (MA_NUMERO,MA_LOCALITE,MA_NOM_GERANT,MA_PRENOM_GERANT) values ('M01','CAEN','GOSSELIN','Pierre');
insert into BUR_MAGASIN (MA_NUMERO,MA_LOCALITE,MA_NOM_GERANT,MA_PRENOM_GERANT) values ('M02','CHERBOURG','LEMOINE','Sophie');
insert into BUR_MAGASIN (MA_NUMERO,MA_LOCALITE,MA_NOM_GERANT,MA_PRENOM_GERANT) values ('M03','ROUEN','FONTAINE','Karim');
insert into BUR_MAGASIN (MA_NUMERO,MA_LOCALITE,MA_NOM_GERANT,MA_PRENOM_GERANT) values ('M04','BAYEUX','GOSSELIN','Marie');

-- BUR_FOURNISSEUR (7 lignes)
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F01','PAPETERIES NORMANDES');
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F02','STYLO PLUS');
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F03','BUREAU EXPRESS');
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F04','CLASSEMENT ET CIE');
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F05','ENCRES DU NORD');
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F06','MOBILIER PRO');
insert into BUR_FOURNISSEUR (FO_NUMERO,FO_NOM) values ('F07','ECO BUREAU');

-- BUR_ARTICLE (20 lignes)
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A01','F02','STYLO BILLE',12,'BLEU',500,0.2,0.6);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A02','F02','STYLO BILLE',12,'ROUGE',300,0.2,0.6);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A03','F02','STYLO PLUME',25,'NOIR',40,4.5,12.0);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A04','F01','RAMETTE A4',2500,'BLANC',120,3.1,5.9);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A05','F01','RAMETTE A3',5000,'BLANC',30,6.8,11.5);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A06','F01','BLOC NOTES',180,'JAUNE',200,0.9,2.4);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A07','F03','AGRAFEUSE',350,'ROUGE',45,4.0,9.9);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A08','F03','PERFORATRICE',420,'NOIR',35,5.2,11.9);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A09','F03','CISEAUX',90,'ROUGE',60,1.5,3.9);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A10','F04','CLASSEUR',300,'VERT',150,1.8,4.5);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A11','F04','CLASSEUR',300,'ROUGE',80,1.8,4.5);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A12','F04','CHEMISE CARTON',40,'BLEU',400,0.15,0.5);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A13','F04','BOITE ARCHIVE',650,null,70,2.3,5.2);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A14','F05','CARTOUCHE ENCRE',60,'NOIR',90,18.0,34.9);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A15','F05','CARTOUCHE ENCRE',60,'BLEU',50,18.0,34.9);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A16','F05','SURLIGNEUR',15,'JAUNE',250,0.4,1.2);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A17','F06','LAMPE DE BUREAU',1200,'NOIR',15,14.0,32.0);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A18','F06','FAUTEUIL',14000,'NOIR',6,75.0,149.0);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A19','F03','GOMME',20,'BLANC',300,null,0.8);
insert into BUR_ARTICLE (AR_NUMERO,FO_NUMERO,AR_NOM,AR_POIDS,AR_COULEUR,AR_STOCK,AR_PA,AR_PV) values ('A20','F02','CRAYON PAPIER',6,null,1000,null,0.3);

-- BUR_COMMANDE (12 lignes)
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K01',to_date('08/01/2025','DD/MM/YYYY'),'M01','C01');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K02',to_date('15/01/2025','DD/MM/YYYY'),'M01','C03');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K03',to_date('03/02/2025','DD/MM/YYYY'),'M02','C02');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K04',to_date('20/02/2025','DD/MM/YYYY'),'M01','C01');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K05',to_date('11/03/2025','DD/MM/YYYY'),'M03','C04');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K06',to_date('28/03/2025','DD/MM/YYYY'),'M02','C10');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K07',to_date('02/04/2025','DD/MM/YYYY'),'M01','C07');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K08',to_date('14/05/2025','DD/MM/YYYY'),'M03','C09');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K09',to_date('05/06/2025','DD/MM/YYYY'),'M04','C06');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K10',to_date('30/06/2025','DD/MM/YYYY'),'M01','C03');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K11',to_date('09/09/2025','DD/MM/YYYY'),'M02','C02');
insert into BUR_COMMANDE (CO_NUMERO,CO_DATE,MA_NUMERO,CL_NUMERO) values ('K12',to_date('01/10/2025','DD/MM/YYYY'),'M01','C01');

-- BUR_LIGCDE (25 lignes)
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K01','A04',20,20,5.9,to_date('10/01/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K01','A01',100,100,0.6,to_date('10/01/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K01','A07',2,2,9.9,to_date('10/01/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K02','A10',30,30,4.5,to_date('20/01/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K02','A12',200,200,0.5,to_date('20/01/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K03','A03',1,1,12.0,to_date('06/02/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K03','A06',5,5,2.4,to_date('06/02/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K04','A14',6,6,34.9,to_date('25/02/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K04','A04',40,30,5.9,to_date('25/02/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K05','A18',2,2,149.0,to_date('18/03/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K05','A17',2,2,32.0,to_date('18/03/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K05','A05',10,10,11.5,to_date('18/03/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K06','A02',10,10,0.6,to_date('01/04/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K07','A09',1,1,3.9,to_date('03/04/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K07','A16',4,4,1.2,to_date('03/04/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K07','A11',3,3,4.5,to_date('03/04/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K08','A15',12,12,34.9,to_date('20/05/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K08','A08',3,3,11.9,to_date('20/05/2025','DD/MM/YYYY'));
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K09','A01',20,0,0.6,null);
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K09','A06',10,0,2.4,null);
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K10','A04',25,0,5.9,null);
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K10','A13',10,0,5.2,null);
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K11','A07',1,0,9.9,null);
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K12','A18',1,0,149.0,null);
insert into BUR_LIGCDE (CO_NUMERO,AR_NUMERO,LIC_QTCMDEE,LIC_QTLIVREE,LIC_PU,DATE_LIV) values ('K12','A14',4,0,34.9,null);

-- BUR_LIVRAISON (8 lignes)
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L01','M01','K01','C01',to_date('10/01/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L02','M01','K02','C03',to_date('20/01/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L03','M02','K03','C02',to_date('06/02/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L04','M01','K04','C01',to_date('25/02/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L05','M03','K05','C04',to_date('18/03/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L06','M02','K06','C10',to_date('01/04/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L07','M01','K07','C07',to_date('03/04/2025','DD/MM/YYYY'));
insert into BUR_LIVRAISON (LI_NUMERO,MA_NUMERO,CO_NUMERO,CL_NUMERO,DATE_LIV) values ('L08','M03','K08','C09',to_date('20/05/2025','DD/MM/YYYY'));

-- BUR_LIGLIV (18 lignes)
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L01','A04',20);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L01','A01',100);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L01','A07',2);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L02','A10',30);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L02','A12',200);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L03','A03',1);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L03','A06',5);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L04','A14',6);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L04','A04',30);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L05','A18',2);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L05','A17',2);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L05','A05',10);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L06','A02',10);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L07','A09',1);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L07','A16',4);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L07','A11',3);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L08','A15',12);
insert into BUR_LIGLIV (LI_NUMERO,AR_NUMERO,LIL_QTLIVREE) values ('L08','A08',3);

commit;
